CREATE SCHEMA IF NOT EXISTS S_ACCOUNT;

CREATE TABLE T_ACCOUNT (
  ID UUID PRIMARY KEY,
  OWNER VARCHAR,
  BALANCE DECIMAL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  VERSION BIGINT
);
