CREATE SCHEMA IF NOT EXISTS S_ORDER;

CREATE TABLE T_ORDER (
  ID BIGSERIAL PRIMARY KEY,
  ACCOUNT_ID  UUID NOT NULL,
  TOTAL DECIMAL NOT NULL,
  CREATION_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  VERSION BIGINT,
  STATUS VARCHAR NOT NULL,
  DESCRIPTION VARCHAR
);
