server.servlet.context-path: / # Context path of the application.
server.compression.enabled: true
server.compression.mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size: 1024
server.http2.enabled: true
server.port: ${SERVER_PORT:8080}

spring.application.name: '@project.artifactId@'
spring.application.version: '@project.version@'
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:local}
spring.main.allow-bean-definition-overriding: true # Enable bean override

---
spring.config.activate.on-profile: local

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
# ENDPOINTS WEB CONFIGURATION
management.endpoints.web.exposure.include: '*' # Endpoint IDs that should be included or '*' for all.
management.endpoints.web.exposure.exclude:  # Endpoint IDs that should be excluded or '*' for all.
management.endpoints.web.base-path: /management # Base path for Web endpoints. Relative to server.servlet.context-path or management.server.servlet.context-path if management.server.port is configured.
management.endpoints.web.path-mapping.health: healthcheck

# HEALTH ENDPOINT
management.endpoint.health.cache.time-to-live: 0ms # Maximum time that a response can be cached.
management.endpoint.health.enabled: true # Whether to enable the health endpoint.
management.endpoint.health.roles:  # Roles used to determine whether or not a user is authorized to be shown details. When empty, all authenticated users are authorized.
management.endpoint.health.show-details: always # When to show full health details.

# INFO CONTRIBUTORS (InfoContributorProperties)
management.info.build.enabled: true # Whether to enable build info.
management.info.defaults.enabled: true # Whether to enable default info contributors.
management.info.env.enabled: true # Whether to enable environment info.
management.info.git.enabled: true # Whether to enable git info.
management.info.git.mode: full # Mode to use to expose git information.

# METRICS :: DATADOG
management.datadog.metrics.export.enabled: false
management.datadog.metrics.export.api-key: "YOUR_API_KEY"
management.datadog.metrics.export.uri: https://api.datadoghq.eu
management.datadog.metrics.export.step: 30s
#--
management.statsd.metrics.export.enabled: false
management.statsd.metrics.export.host: localhost
management.statsd.metrics.export.port: 8125
management.statsd.metrics.export.protocol: udp
management.statsd.metrics.export.flavor: datadog
#--
management.metrics.tags:
  application: ${spring.application.name}
  env: ${spring.profiles.active}
  environment: ${spring.profiles.active}

# LOGGING
logging.config: classpath:log4j2.xml # Location of the logging configuration file. For instance, `classpath:logback.xml` for Logback.
logging.level: # Log levels severity mapping. For instance, `logging.level.org.springframework: DEBUG`.
  org.springframework: INFO
  org.springframework.cloud.sleuth: TRACE
  org.flywaydb: INFO
  com.cjrequena.sample: DEBUG

# https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/
#spring.cloud.function.definition: consumer1, consumer2
spring.cloud.function.definition: consumer1
spring.cloud.stream:
  defaultBinder: kinesis # The default binder to use, if multiple binders are configured. See Multiple Binders on the Classpath.
  default:
    content-type: application/json
spring.cloud.stream.bindings:
  consumer1-in-0:
    binder: kinesis # The binder used by this binding. See Multiple Binders on the Classpath for details.
    destination: spring-cloud-stream-kinesis-sample-01 # The target destination of a channel on the bound middleware (e.g., the RabbitMQ exchange or Kafka topic).
    group: group-1 # The consumer group of the channel. Applies only to inbound bindings. See Consumer Groups.
    content-type: application/json # The content type of the channel.
    consumer:
      useNativeDecoding: true
  consumer2-in-0:
    binder: kinesis # The binder used by this binding. See Multiple Binders on the Classpath for details.
    destination: spring-cloud-stream-kinesis-sample-01 # The target destination of a channel on the bound middleware (e.g., the RabbitMQ exchange or Kafka topic).
    group: group-1 # The consumer group of the channel. Applies only to inbound bindings. See Consumer Groups.
    content-type: application/json # The content type of the channel.
#
spring.cloud.sleuth.json.enabled: false
#
cloud.aws.credentials.access-key: {YOUR-ACCESS-KEY}
cloud.aws.credentials.secret-key: {YOUR-SECRET-KEY}
cloud.aws.region.static: us-east-1
cloud.aws.stack.auto: false


# OPENAPI :: SPRINGDOC :: SWAGGER
springdoc:
  api-docs:
    groups.enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
    display-request-duration: true
    groups-order: DESC
    operations-sorter: alpha
    tags-sorter: alpha

#
server.compression:
  enabled: true
  mime-types: application/json,application/stream+json,application/x-ndjson
  min-response-size: 1024
