CREATE SCHEMA IF NOT EXISTS S_ORDER;

CREATE TABLE T_ORDER (
  ID BIGSERIAL PRIMARY KEY,
  ACCOUNT_ID  UUID NOT NULL,
  TOTAL DECIMAL NOT NULL,
  DESCRIPTION VARCHAR,
  STATUS VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  VERSION BIGINT
);
