subcompatibility: BACKWARD
subjects:
  # a subject that links to a file for the schema definition
  - name: spring-cloud-stream-kafka-sample-01-value
    # sets compatibility level for this subject (optional)
    compatibility: NONE
    # file paths are always relative to the given (this) YAML file
    file: foo-event.json
    # AVRO is the default type and can safely be omitted (only available for Schema Registry >= 5.5)
    type: JSON
