version: '3.8'

services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    hostname: "postgres"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: "/data/postgres"
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: "postgres"
        target: "/data/postgres"
      #- $PWD/V1.0__account_db.sql:/docker-entrypoint-initdb.d/1-account_db.sql
      #- $PWD/V1.0__order_db.sql:/docker-entrypoint-initdb.d/1-order_db.sql
    networks:
      - "network.local"
    restart: unless-stopped
#---------------------------------------------------------------------------------------------------------------------
networks:
  network.local:
    name: "network.local"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
#---------------------------------------------------------------------------------------------------------------------
volumes:
  postgres:
    name: "postgres"
